# Generated by Django 4.2.4 on 2023-09-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscribedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('mobile', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('transaction', models.CharField(max_length=122)),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
