# Generated by Django 4.2.4 on 2023-09-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_join_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('mobile', models.CharField(max_length=122)),
                ('stuclass', models.CharField(max_length=122)),
                ('aadharcard', models.CharField(max_length=122)),
                ('dob', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
